### ISSUE TITLE
Can't get camera feed to display for a picamera v1

### ISSUE THREAD

**Issue by peyton-howe** [franmora/tearing#1]
Hello, I am trying to use your code as a fast-track from the camera feed -> openGL that I will later modify to use two camera feeds and apply barrel distortion to create a VR display on the Pi. Unfortunately, I cannot get the camera feed to display using a picamera v1 camera, I only get a black screen with error messages.

When running the code, I get the following error message after listing out all of the V4L2 capture formats:
`VIDIOC_QUERY_DV_TIMINGS: Unknown error -1`

The code proceeds to then list the ISP output formats, buffer indexes and textures, as well as creating images #0, 1, and 2 before throwing these error messages:
```
VIDIOC_STREAMON: Unknown error -1
VIDIOC_DQBUF: Unknown error -1
VIDIOC_QBUF: Unknown error -1
```

Any idea how to fix this? 

Note: When I run libcamera-hello, the camera feed is displayed without any issues, so I'm thinking it has to do with the v1 camera module I am trying to use since you used a tc358743.

**Comment by franmora** [comment]
Hello, glad to see someone is interested in the code :-) 
Try to use the following command on the commandline to see if the camera driver is supported and working: 
v4l2-ctrl --query-dv-timings
If that does not give you meaningful TV timings that could be the reason. Also try to check with vlc (Video Loan Client).
Thank you.

**Comment by peyton-howe** [comment]
Running the v4l2-ctl --query-dv-timings command, this is the output I get:
```
VIDIOC_QUERY_DV_TIMINGS: failed: Inappropriate ioctl for device
	Active width: 0
	Active height: 0
	Total width: 0
	Total height: 0
	Frame format: progressive
	Polarities: -vsync -hsync
	Pixelclock: 0 Hz
	Horizontal frontporch: 0
	Horizontal sync: 0
	Horizontal backporch: 0
	Vertical fVIDIOC_QUERY_DV_TIMINGS: failed: Inappropriate ioctl for device
	Active width: 0
	Active height: 0
	Total width: 0
	Total height: 0
	Frame format: progressive
	Polarities: -vsync -hsync
	Pixelclock: 0 Hz
	Horizontal frontporch: 0
	Horizontal sync: 0
	Horizontal backporch: 0
	Vertical frontporch: 0
	Vertical sync: 0
	Vertical backporch: 0
	Standards: 
	Flags: rontporch: 0
	Vertical sync: 0
	Vertical backporch: 0
	Standards: 
	Flags: 
```

Not sure why this is the case if I can get libcamera to work just fine for both of the cameras involved. Note: I am running this on a CM4 on Raspbian Bullseye.

**Comment by franmora** [comment]
That is out of my knowledege because my code relies on the data from the ioctl VIDIOC_QUERY_DV_TIMINGS. I think your camera uses something different. Try to ask for help in a raspberry forum.
